# Generated by Django 2.0.3 on 2018-03-21 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openfoodfacts', '0002_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Substitutes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='openfoodfacts.Products')),
                ('replacement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacement', to='openfoodfacts.Products')),
            ],
        ),
    ]
